# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacher_dashboardnew.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_btn = QtWidgets.QPushButton(self.widget)
        self.change_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../new project dbms/ui/icon/menu-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon)
        self.change_btn.setIconSize(QtCore.QSize(14, 14))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn)
        spacerItem = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.user_btn = QtWidgets.QPushButton(self.widget)
        self.user_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../new project dbms/ui/icon/user-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon1)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_4.addWidget(self.user_btn)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ProfileInfo_page = QtWidgets.QWidget()
        self.ProfileInfo_page.setObjectName("ProfileInfo_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ProfileInfo_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.ProfileInfo_page)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 911, 80))
        self.widget_4.setStyleSheet("background-color: rgb(255, 208, 214);")
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(60, 10, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../new project dbms/ui/icon/teacher-32.ico"))
        self.label_2.setObjectName("label_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(-20, 80, 931, 591))
        self.widget_5.setStyleSheet("background-color: rgb(231, 154, 115);")
        self.widget_5.setObjectName("widget_5")
        self.firstName_label1 = QtWidgets.QLabel(self.widget_5)
        self.firstName_label1.setGeometry(QtCore.QRect(80, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName_label1.setFont(font)
        self.firstName_label1.setObjectName("firstName_label1")
        self.institute_label1 = QtWidgets.QLabel(self.widget_5)
        self.institute_label1.setGeometry(QtCore.QRect(490, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.institute_label1.setFont(font)
        self.institute_label1.setObjectName("institute_label1")
        self.department_label1 = QtWidgets.QLabel(self.widget_5)
        self.department_label1.setGeometry(QtCore.QRect(80, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.department_label1.setFont(font)
        self.department_label1.setObjectName("department_label1")
        self.mobileNo_label1 = QtWidgets.QLabel(self.widget_5)
        self.mobileNo_label1.setGeometry(QtCore.QRect(90, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mobileNo_label1.setFont(font)
        self.mobileNo_label1.setObjectName("mobileNo_label1")
        self.lastName_label1 = QtWidgets.QLabel(self.widget_5)
        self.lastName_label1.setGeometry(QtCore.QRect(490, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName_label1.setFont(font)
        self.lastName_label1.setObjectName("lastName_label1")
        self.email_label1 = QtWidgets.QLabel(self.widget_5)
        self.email_label1.setGeometry(QtCore.QRect(500, 270, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_label1.setFont(font)
        self.email_label1.setObjectName("email_label1")
        self.firstName_label2 = QtWidgets.QLabel(self.widget_5)
        self.firstName_label2.setGeometry(QtCore.QRect(190, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName_label2.setFont(font)
        self.firstName_label2.setStyleSheet("background-color: rgb(255, 240, 215);")
        self.firstName_label2.setText("")
        self.firstName_label2.setObjectName("firstName_label2")
        self.department_label2 = QtWidgets.QLabel(self.widget_5)
        self.department_label2.setGeometry(QtCore.QRect(200, 180, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.department_label2.setFont(font)
        self.department_label2.setStyleSheet("background-color: rgb(255, 240, 215);")
        self.department_label2.setText("")
        self.department_label2.setObjectName("department_label2")
        self.mobileNo_label2 = QtWidgets.QLabel(self.widget_5)
        self.mobileNo_label2.setGeometry(QtCore.QRect(180, 270, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mobileNo_label2.setFont(font)
        self.mobileNo_label2.setStyleSheet("background-color: rgb(255, 240, 215);")
        self.mobileNo_label2.setText("")
        self.mobileNo_label2.setObjectName("mobileNo_label2")
        self.lastName_label2 = QtWidgets.QLabel(self.widget_5)
        self.lastName_label2.setGeometry(QtCore.QRect(590, 90, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName_label2.setFont(font)
        self.lastName_label2.setStyleSheet("background-color: rgb(255, 240, 215);")
        self.lastName_label2.setText("")
        self.lastName_label2.setObjectName("lastName_label2")
        self.email_label2 = QtWidgets.QLabel(self.widget_5)
        self.email_label2.setGeometry(QtCore.QRect(560, 270, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_label2.setFont(font)
        self.email_label2.setStyleSheet("background-color: rgb(255, 240, 215);")
        self.email_label2.setText("")
        self.email_label2.setObjectName("email_label2")
        self.institute_label2 = QtWidgets.QLabel(self.widget_5)
        self.institute_label2.setGeometry(QtCore.QRect(570, 180, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.institute_label2.setFont(font)
        self.institute_label2.setStyleSheet("background-color: rgb(255, 240, 215);")
        self.institute_label2.setText("")
        self.institute_label2.setObjectName("institute_label2")
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.ProfileInfo_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.page_2)
        self.widget_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 911, 80))
        self.widget_7.setStyleSheet("background-color: rgb(154, 152, 200);")
        self.widget_7.setObjectName("widget_7")
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 47, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../new project dbms/ui/icon/literature-32.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setGeometry(QtCore.QRect(0, 80, 911, 591))
        self.widget_8.setObjectName("widget_8")
        self.viewCourse_tableWidget = QtWidgets.QTableWidget(self.widget_8)
        self.viewCourse_tableWidget.setGeometry(QtCore.QRect(0, 0, 911, 581))
        self.viewCourse_tableWidget.setStyleSheet("background-color: rgb(235, 255, 254);")
        self.viewCourse_tableWidget.setObjectName("viewCourse_tableWidget")
        self.viewCourse_tableWidget.setColumnCount(4)
        self.viewCourse_tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewCourse_tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.widget_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.page_3)
        self.widget_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setGeometry(QtCore.QRect(0, 0, 911, 80))
        self.widget_10.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.widget_10.setObjectName("widget_10")
        self.label_5 = QtWidgets.QLabel(self.widget_10)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../new project dbms/ui/icon/iconfinder-515-best-grade-achieve-education-4212899_114954.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        self.label_6.setGeometry(QtCore.QRect(110, 20, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setGeometry(QtCore.QRect(0, 80, 911, 581))
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        self.widget_12.setGeometry(QtCore.QRect(0, 0, 911, 111))
        self.widget_12.setStyleSheet("background-color: rgb(240, 149, 165);")
        self.widget_12.setObjectName("widget_12")
        self.course_label_8 = QtWidgets.QLabel(self.widget_12)
        self.course_label_8.setGeometry(QtCore.QRect(50, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.course_label_8.setFont(font)
        self.course_label_8.setObjectName("course_label_8")
        self.course_comboBox = QtWidgets.QComboBox(self.widget_12)
        self.course_comboBox.setGeometry(QtCore.QRect(130, 50, 251, 22))
        self.course_comboBox.setStyleSheet("background-color: rgb(244, 255, 228);")
        self.course_comboBox.setObjectName("course_comboBox")
        self.apply_pushButton = QtWidgets.QPushButton(self.widget_12)
        self.apply_pushButton.setGeometry(QtCore.QRect(750, 50, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.apply_pushButton.setFont(font)
        self.apply_pushButton.setStyleSheet("background-color: rgb(189, 113, 127);")
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_11)
        self.textBrowser.setGeometry(QtCore.QRect(0, 110, 911, 121))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 250, 222);")
        self.textBrowser.setObjectName("textBrowser")
        self.widget_13 = QtWidgets.QWidget(self.widget_11)
        self.widget_13.setGeometry(QtCore.QRect(0, 230, 911, 361))
        self.widget_13.setStyleSheet("background-color: rgb(255, 253, 226);")
        self.widget_13.setObjectName("widget_13")
        self.student_label = QtWidgets.QLabel(self.widget_13)
        self.student_label.setGeometry(QtCore.QRect(40, 31, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.student_label.setFont(font)
        self.student_label.setObjectName("student_label")
        self.student_comboBox = QtWidgets.QComboBox(self.widget_13)
        self.student_comboBox.setGeometry(QtCore.QRect(120, 30, 221, 22))
        self.student_comboBox.setStyleSheet("background-color: rgb(194, 191, 169);")
        self.student_comboBox.setObjectName("student_comboBox")
        self.markGrade_label = QtWidgets.QLabel(self.widget_13)
        self.markGrade_label.setGeometry(QtCore.QRect(530, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.markGrade_label.setFont(font)
        self.markGrade_label.setObjectName("markGrade_label")
        self.markGrade_comboBox = QtWidgets.QComboBox(self.widget_13)
        self.markGrade_comboBox.setGeometry(QtCore.QRect(650, 30, 101, 22))
        self.markGrade_comboBox.setStyleSheet("background-color: rgb(194, 191, 169);")
        self.markGrade_comboBox.setObjectName("markGrade_comboBox")
        self.submit_pushButton = QtWidgets.QPushButton(self.widget_13)
        self.submit_pushButton.setGeometry(QtCore.QRect(360, 180, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submit_pushButton.setFont(font)
        self.submit_pushButton.setStyleSheet("background-color: rgb(157, 149, 139);")
        self.submit_pushButton.setObjectName("submit_pushButton")
        self.gridLayout_4.addWidget(self.widget_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_label_1 = QtWidgets.QLabel(self.icon_only_widget)
        self.logo_label_1.setMinimumSize(QtCore.QSize(50, 50))
        self.logo_label_1.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_label_1.setText("")
        self.logo_label_1.setPixmap(QtGui.QPixmap("../new project dbms/ui/icon/Picture1.png"))
        self.logo_label_1.setScaledContents(True)
        self.logo_label_1.setObjectName("logo_label_1")
        self.horizontalLayout_3.addWidget(self.logo_label_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../new project dbms/ui/icon/administrator-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_1.setIcon(icon2)
        self.home_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout.addWidget(self.home_btn_1)
        self.dashborad_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.dashborad_btn_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../new project dbms/ui/icon/literature-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashborad_btn_1.setIcon(icon3)
        self.dashborad_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.dashborad_btn_1.setCheckable(True)
        self.dashborad_btn_1.setAutoExclusive(True)
        self.dashborad_btn_1.setObjectName("dashborad_btn_1")
        self.verticalLayout.addWidget(self.dashborad_btn_1)
        self.orders_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.orders_btn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../new project dbms/ui/icon/3709746-customer-evaluation-review-satisfaction-system_108070.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.orders_btn_1.setIcon(icon4)
        self.orders_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.orders_btn_1.setCheckable(True)
        self.orders_btn_1.setAutoExclusive(True)
        self.orders_btn_1.setObjectName("orders_btn_1")
        self.verticalLayout.addWidget(self.orders_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../admin menue bar/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(icon5)
        self.exit_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setText("")
        self.logo_label_2.setPixmap(QtGui.QPixmap("../new project dbms/ui/icon/Picture1.png"))
        self.logo_label_2.setScaledContents(True)
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout_2.addWidget(self.logo_label_2)
        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setObjectName("logo_label_3")
        self.horizontalLayout_2.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profile_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.profile_btn_2.setIcon(icon2)
        self.profile_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.profile_btn_2.setCheckable(True)
        self.profile_btn_2.setAutoExclusive(True)
        self.profile_btn_2.setObjectName("profile_btn_2")
        self.verticalLayout_2.addWidget(self.profile_btn_2)
        self.view_course_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.view_course_btn_2.setIcon(icon3)
        self.view_course_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.view_course_btn_2.setCheckable(True)
        self.view_course_btn_2.setAutoExclusive(True)
        self.view_course_btn_2.setObjectName("view_course_btn_2")
        self.verticalLayout_2.addWidget(self.view_course_btn_2)
        self.mark_grade_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.mark_grade_btn_2.setIcon(icon4)
        self.mark_grade_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.mark_grade_btn_2.setCheckable(True)
        self.mark_grade_btn_2.setAutoExclusive(True)
        self.mark_grade_btn_2.setObjectName("mark_grade_btn_2")
        self.verticalLayout_2.addWidget(self.mark_grade_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../new project dbms/ui/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_2.setIcon(icon6)
        self.exit_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.home_btn_1.toggled['bool'].connect(self.profile_btn_2.setChecked) # type: ignore
        self.orders_btn_1.toggled['bool'].connect(self.mark_grade_btn_2.setChecked) # type: ignore
        self.profile_btn_2.toggled['bool'].connect(self.home_btn_1.setChecked) # type: ignore
        self.mark_grade_btn_2.toggled['bool'].connect(self.orders_btn_1.setChecked) # type: ignore
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.exit_btn_1.clicked.connect(MainWindow.close) # type: ignore
        self.dashborad_btn_1.toggled['bool'].connect(self.view_course_btn_2.setChecked) # type: ignore
        self.view_course_btn_2.toggled['bool'].connect(self.dashborad_btn_1.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# Add custom styles directly here
        MainWindow.setStyleSheet("""
        /*= Style for mainwindow START
        ==================================================== */
        #MainWindow {
            background-color: #fff;
        }
        /*= END
        ==================================================== */

        /*= Style for button to change menu style START
        ==================================================== */
        #change_btn {
            padding: 5px;
            border: none;
            width: 30px;
            height: 30px;
        }
        /*= END
        ==================================================== */

        /*= Style for header widget START
        ==================================================== */
        #widget {
            background-color: #f9fafd;
        }
        /*= END
        ==================================================== */

        /*= Style for menu with icon only START
        ==================================================== */
        #icon_only_widget {
            background-color: #B0C4DE; /* Changed to a lighter color */
            width: 50px;
        }

        #icon_only_widget QPushButton, QLabel {
            height: 50px;
            border: none;
            color: #000; /* Set button text color to black */
        }

        #icon_only_widget QPushButton:hover {
            background-color: rgba(86, 101, 115, 0.5);
        }

        #logo_label_1 {
            padding: 5px;
        }
        /*= END
        ==================================================== */

        /*= Style for menu with icon and text START
        ==================================================== */
        #full_menu_widget {
            background-color: #B0C4DE; /* Changed to a lighter color */
        }

        #full_menu_widget QPushButton {
            border: none;
            border-radius: 3px;
            text-align: left;
            padding: 8px 0 8px 15px;
            color: #000; /* Set button text color to black */
        }

        #full_menu_widget QPushButton:hover {
            background-color: rgba(86, 101, 115, 0.5);
        }

        #full_menu_widget QPushButton:checked {
            color: #fff;
        }

        #logo_label_2 {
            padding: 5px;
            color: #fff;
        }

        #logo_label_3 {
            padding-right: 10px;
            color: #fff;
        }
        /*= END
        ==================================================== */

        /*= Style for search button START
        ==================================================== */
        #search_btn {
            border: none;
            color: #000; /* Set search button text color to black */
        }
        /*= END
        ==================================================== */

        /*= Style for search input START
        ==================================================== */
        #search_input {
            border: none;
            padding: 5px 10px;
            color: #000; /* Set search input text color to black */
        }

        #search_input:focus {
            background-color: #70B9FE;
        }
        /*= END
        ==================================================== */

        /*= Style for user information button START
        ==================================================== */
        #user_btn {
            border: none;
            color: #000; /* Set user button text color to black */
        }
        /*= END
        ==================================================== */
        """)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Profile Info"))
        self.firstName_label1.setText(_translate("MainWindow", "FirstNames"))
        self.institute_label1.setText(_translate("MainWindow", "Institute"))
        self.department_label1.setText(_translate("MainWindow", "Department"))
        self.mobileNo_label1.setText(_translate("MainWindow", "MobileNo"))
        self.lastName_label1.setText(_translate("MainWindow", "LastName"))
        self.email_label1.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "View Course"))
        item = self.viewCourse_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.viewCourse_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.viewCourse_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.viewCourse_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.viewCourse_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.viewCourse_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.viewCourse_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CourseCode"))
        item = self.viewCourse_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CourseTitle"))
        item = self.viewCourse_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "cradit"))
        item = self.viewCourse_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Semester"))
        self.label_6.setText(_translate("MainWindow", "Mark Grade"))
        self.course_label_8.setText(_translate("MainWindow", "Course"))
        self.apply_pushButton.setText(_translate("MainWindow", "Apply"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Welcome to the Grade Marking section. As a teacher, you can record and manage the grades for your students here. Follow the steps below to mark grades:</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:7pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Select Course</span>: Choose the course from the dropdown menu.</li>\n"
"<li style=\" font-size:7pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Select Student</span>: After selecting the course, choose the student from the list.</li>\n"
"<li style=\" font-size:7pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Mark Grade</span>: Enter the grade in the provided field.</li>\n"
"<li style=\" font-size:7pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Submit Grades</span>: Click the \'Submit\' button to save the grade.</li></ol></body></html>"))
        self.student_label.setText(_translate("MainWindow", "Student"))
        self.markGrade_label.setText(_translate("MainWindow", "Mark Grade"))
        self.submit_pushButton.setText(_translate("MainWindow", "Submit"))
        self.logo_label_3.setText(_translate("MainWindow", "CMS"))
        self.profile_btn_2.setText(_translate("MainWindow", "profile"))
        self.view_course_btn_2.setText(_translate("MainWindow", "view course"))
        self.mark_grade_btn_2.setText(_translate("MainWindow", "mark grade"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

